### PR TITLE
Posix support

### PR DESCRIPTION
**Pull request by diegoiast**
This patch adds support for compilation under linux and Mac. With some luck - other unixes will compile.

The reason for this - is to ease development of this app. IMHO, we have better tooling on Linux (for example better editor, real multi tasking, good debuggers and valgrind). 

I also started changing the code under `echo` and I am using coding formats more suitable for C (more code can be seen on a single page). 

The code crashes on Linux, and this is something I am addressing on another patch, as soon as this is accepted.

### CODE REVIEW

**Comment by ercanersoy** [comment]
Thanks for interesting. The contributed codes are written by you or other people?

**Comment by ercanersoy** [comment]
You should be keep the coding standards that have existed.

**Comment by diegoiast** [comment]
All code was written by me.

**Comment by diegoiast** [comment]
.. and reverted back to original indentation, and coding standards

**Comment by ercanersoy** [comment]
May you change the given below?
-  `for(; i < argc; i++)` to `for(i; i < argc; i++)`
-  All case statements should be
  `case ...:`
     `...` (with indent)
  `break;` (with indent)

**Comment by diegoiast** [comment]
There is a reason I removed the variable, from the `for` initialisation segment. The original code just put the variable, which produces a warning (yes, "23" is not a useful statement). Why do you need them?

**Comment by ercanersoy** [comment]
> There is a reason I removed the variable, from the `for` initialisation segment. The original code just put the variable, which produces a warning (yes, "23" is not a useful statement). Why do you need them?

You are right. You shouldn't put the variable. Thanks.

**Comment by ercanersoy** [comment]
> May you change the given below?
> 
>     * `for(; i < argc; i++)` to `for(i; i < argc; i++)`
> 
>     * All case statements should be
>       `case ...:`
>       `...` (with indent)
>       `break;` (with indent)

I updated 1 hour ago this comment. break statement in switch-case blocks don't need extra indent. May you delete extra indents on break statements?

**Comment by diegoiast** [comment]
See 5572c1d - but please verify that it compiles with your compiler before merging. I tried yesterday installing ia16-gcc, and it behaves different (for example, Borland's make does not like "\" for file names). I still have not tested djgpp, not TurboC.

**Comment by ercanersoy** [comment]
May you delete extra indents on break statements? Thanks.

> See [5572c1d](https://github.com/ercanersoy/Minibox/commit/5572c1dcdbbfc7ce0f962961cb839cb843fb1302) - but please verify that it compiles with your compiler before merging. I tried yesterday installing ia16-gcc, and it behaves different (for example, Borland's make does not like "" for file names). I still have not tested djgpp, not TurboC.

I'm using DJGPP 9.1.0 for Minibox.

**Pull request closed without merging**
